name: Lint Docker
on:
  push: null
jobs:
  Hadolint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: brpaz/hadolint-action@master
      with:
        dockerfile: Dockerfile
  DockerCompose:
    runs-on: ubuntu-latest
    needs: Hadolint
    steps:
    - uses: actions/checkout@v1
    - name: Validates Docker Compose files
      run: "find . -name docker-compose.yml -print |\n  while read file; do\n    docker compose -f $file\
        \ config -q || exit 1\n  done\n"
